#cloud-config
package_update: true
package_upgrade: true
packages:
- docker

#cloud-config
users:
- name: alex
  groups: sudo
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKsdtGbkSm5g0QFynyWvjpzWj53CEr8hx8xSkQ7w5Mvl Alex Linode 2024