version: '3.8'

services:
  wysiwyg-editor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wysiwyg-editor
    restart: unless-stopped
    ports:
      - "3011:3000"
    environment:
      # Application settings
      NODE_ENV: production
      PORT: 3000
      PUBLIC_BASE_URL: ${PUBLIC_BASE_URL:-http://localhost:3011}
      
      # S3 Configuration
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_FORCE_PATH_STYLE: ${S3_FORCE_PATH_STYLE}
    
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  # Optional: Add nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: wysiwyg-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - wysiwyg-editor
    profiles:
      - production